doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    profiling_collect_backtrace: '%kernel.debug%'
    types:
      code: App\Shared\Infrastructure\Persistence\Doctrine\Type\DoctrineCodeType
      cost: App\Shared\Infrastructure\Persistence\Doctrine\Type\DoctrineCostType
      ingredient_id: App\Content\Infrastructure\Persistence\Doctrine\Type\DoctrineIngredientIdType
      json_string: App\Shared\Infrastructure\Persistence\Doctrine\Type\DoctrineJsonStringType
      localized_string: App\Shared\Infrastructure\Persistence\Doctrine\Type\DoctrineLocalizedStringType

  orm:
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
    auto_mapping: true

    mappings:
      ContentDomain:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Content/Infrastructure/Persistence/Doctrine/resources'
        prefix: 'App\Content\Domain\Model'
        alias: ContentDomain

      SharedDomain:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/resources'
        prefix: 'App\Shared\Domain\Event'
        alias: SharedDomain

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system