services:
    php:
        container_name: pizzouille-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                UID: ${HOST_UID}
                GID: ${HOST_GID}
        volumes:
            - .:/var/www/pizzouille-api:cached
        depends_on:
            - db
            - rabbitmq
        entrypoint: ["sh", "/usr/local/bin/docker-entrypoint.sh"]
        working_dir: /var/www/pizzouille-api
        user: www-data

    nginx:
        container_name: pizzouille-nginx
        image: nginx:1.29
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - .:/var/www/pizzouille-api:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/certs:/etc/nginx/ssl:ro
        depends_on:
            - php

    db:
        container_name: pizzouille-db
        image: postgres:17
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data

    rabbitmq:
        container_name: pizzouille-rabbitmq
        image: rabbitmq:4-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    pgadmin:
        container_name: pizzouille-pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - db

volumes:
    db_data:
    pgadmin_data:
