<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250923202040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates "event" table"';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
            CREATE TABLE event (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                aggregate_id UUID NOT NULL,
                type TEXT NOT NULL,
                body JSONB NOT NULL,
                occurred_on TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE event');
    }
}
