<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250923202040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates "event" table"';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE event (type VARCHAR(255) NOT NULL, body JSON NOT NULL, occurred_on TIMESTAMP(0) WITH TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE event');
    }
}
