parameters:
    app.default_locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultLocale: '%app.default_locale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Application/**/{*Command.php,*Query.php}'
            - '../src/*/Domain/{Model,Event,Exception,ValueObject}/'
            - '../src/*/UI/Http/**/Request/'
            - '../src/*/UI/Http/**/Response/'
            - '../src/Shared/Domain/Event/StoredEvent.php'
            - '../src/Kernel.php'

    # Re-include some services
    App\Shared\Domain\Model\CodeFactory: ~
    App\Shared\Domain\Event\EventStoreInterface:
        alias: App\Shared\Infrastructure\Event\DoctrineEventStore

    _instanceof:
        App\Shared\UI\Http\ControllerInterface:
            tags: ['controller.service_arguments']
            public: true

        App\Shared\Application\Bus\Command\CommandHandlerInterface:
            tags: ['app.command_handler']

        App\Shared\Application\Bus\Event\DomainEventSubscriberInterface:
            tags: ['app.domain_event_subscriber']

    # Command Bus Configuration
    App\Shared\Application\Bus\Command\CommandBusInterface:
        alias: App\Shared\Infrastructure\Bus\Command\SymfonyInMemoryCommandBus

    App\Shared\Infrastructure\Bus\Command\SymfonyInMemoryCommandBus:
        arguments:
            $commandHandlers: !tagged_iterator app.command_handler

    Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware: ~

    App\Shared\Infrastructure\Bus\Command\Middleware\DomainEventsMiddleware: ~

    # Event Bus Configuration
    App\Shared\Infrastructure\Bus\Event\SymfonyInMemoryEventBus:
        arguments:
            $subscribers: !tagged_iterator app.domain_event_subscriber

    App\Shared\Application\Bus\Event\EventBusInterface:
        alias: App\Shared\Infrastructure\Bus\Event\SymfonyInMemoryEventBus
